fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall.git"
    sysctl: "https://github.com/duritong/puppet-sysctl.git"
  symlinks:
    archlinux_macbookretina: "#{source_dir}"
