# Class: archlinux_macbookretina
#
# Manage includes of other archlinux_macbookretina classes
# top-level class for archlinux_macbookretina ecosystem
#
# WARNING - WARNING - this file is generated by makeinitpp.sh.
#   any local changes will be overwritten.
#
# Parameters:
#
# Actions:
#   - Include other classes
#
# Requires:
#
# Sample Usage:
#
class archlinux_macbookretina {

  # make sure we're on Arch, otherwise fail
  if $::osfamily != 'Archlinux' {
    fail("${::operatingsystem} not supported")
  }

  case $::productname {
    'MacBookPro10,1': { $cant_have_an_empty_block = true }
    'MacBookPro11,4': { $cant_have_an_empty_block = true }
    default: {
      fail("${::productname} is not a supported hardware productname")
    }
  }

# BLACKLISTED in makeinitpp.sh: laptop_mode_tools
#  # Install and configute laptop-mode-tools for power saving
#  include archlinux_macbookretina::laptop_mode_tools

  # Sets up macbook-specific keyboard stuff
  #include archlinux_macbookretina::mac_keyboard

  # Setup KDM/KDE specific to the MacBook Pro Retina - setup kdmrc
  #include archlinux_macbookretina::mbp_retina_kde

# BLACKLISTED in makeinitpp.sh: nouveau
#  # Install nouveau driver for nvidia graphics and sample xorg.conf. Choose this class OR nvidia.
#  include archlinux_macbookretina::nouveau

  # Install proprietary nvidia driver for nvidia graphics and sample xorg.conf. Choose this class OR nouveau.
  #include archlinux_macbookretina::nvidia

  # Sets up SSD-specific tuning on the system, disks and ext4 partitions
  #include archlinux_macbookretina::ssd

  # Install driver for Broadcom wireless, iw and wpa_supplicant
  include archlinux_macbookretina::wireless

  # Install packages required for xorg X server
  #include archlinux_macbookretina::xorg

}
