# Class: archlinux_macbookretina
#
# Manage includes of other archlinux_macbookretina classes
# top-level class for archlinux_macbookretina ecosystem
#
# WARNING - WARNING - this file is generated by makeinitpp.sh.
#   any local changes will be overwritten.
#
# Parameters:
#
# Actions:
#   - Include other classes
#
# Requires:
#
# Sample Usage:
#
class archlinux_macbookretina {

  # make sure we're on Arch, otherwise fail
  if $::osfamily != 'Archlinux' {
    fail("${::operatingsystem} not supported")
  }

  case $::productname {
    'MacBookPro10,1': { $cant_have_an_empty_block = true }
    'MacBookPro11,4': { $cant_have_an_empty_block = true }
    default: {
      fail("${::productname} is not a supported hardware productname")
    }
  }

  # Install proprietary nvidia driver for nvidia graphics and sample xorg.conf
  class {'archlinux_macbookretina::videodriver':
    driver => 'nvidia', # default
  }

  # Install driver for Broadcom wireless, iw and wpa_supplicant
  include archlinux_macbookretina::wireless

  # setup the apple kernel module for the mac keyboard
  include archlinux_macbookretina::mac_keyboard

  # touchpad setup
  include archlinux_macbookretina::touchpad
}
