HOSTS:
  archlinux-2016.12.01-amd64:
    roles:
      - master
    platform: archlinux-2016.12.01-amd64
    box: ogarcia/archlinux-x64
    box_version: 2016.12.01
    hypervisor: vagrant
    vb_gui: true
CONFIG:
  log_level: verbose
  type: aio
