HOSTS:
  arch-x64:
    roles:
      - master
    platform: archlinux-2015.09.01-amd64
    box: jantman/packer-arch-workstation
    hypervisor: vagrant
    vb_gui: true

CONFIG:
  log_level: verbose
  type: foss
