HOSTS:
  archlinux-2017.07.01-amd64:
    roles:
      - master
    platform: archlinux-2017.07.01-amd64
    box: ogarcia/archlinux-x64
    box_version: 2017.07.01
    hypervisor: vagrant
CONFIG:
  log_level: verbose
  type: aio
